//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcquiredFormation
    {
        public int AcquiredID { get; set; }
        public int EmployeeID { get; set; }
        public int FormationID { get; set; }
        public System.DateTime AcquiredDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Formation Formation { get; set; }
    }
}
