//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirAtlantiqueDRHEntities : DbContext
    {
        public AirAtlantiqueDRHEntities()
            : base("name=AirAtlantiqueDRHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcquiredFormation> AcquiredFormation { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Formation> Formation { get; set; }
        public DbSet<Job> Job { get; set; }
        public DbSet<Login> Login { get; set; }
        public DbSet<Session> Session { get; set; }
    }
}
