//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formation
    {
        public Formation()
        {
            this.AcquiredFormation = new HashSet<AcquiredFormation>();
            this.Session = new HashSet<Session>();
            this.Job = new HashSet<Job>();
        }
    
        public int FormationID { get; set; }
        public string FormationName { get; set; }
        public int ValidityDuration { get; set; }
        public string FormationDescription { get; set; }
    
        public virtual ICollection<AcquiredFormation> AcquiredFormation { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<Job> Job { get; set; }
    }
}
