//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Employee = new HashSet<Employee>();
            this.Formation = new HashSet<Formation>();
        }
    
        public int JobID { get; set; }
        public string JobName { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Formation> Formation { get; set; }
    }
}
