//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAtlantique.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int UserID { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
    }
}
